# Generated by Django 6.0.6 on 2026-06-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="gives_item",
            field=models.CharField(
                blank=True,
                help_text="Item player receives after choosing this",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="required_item",
            field=models.CharField(
                blank=True,
                help_text="Item required to unlock this choice",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="required_scene",
            field=models.CharField(
                blank=True,
                help_text="Scene key that must have been visited",
                max_length=50,
            ),
        ),
    ]
