# Generated by Django 6.0.6 on 2026-06-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_choice_gives_item_choice_required_item_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scene",
            old_name="description",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="gives_item",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="required_item",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="required_scene",
        ),
        migrations.RemoveField(
            model_name="scene",
            name="title",
        ),
        migrations.AlterField(
            model_name="choice",
            name="next_scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_scenes",
                to="game.scene",
            ),
        ),
    ]
